export type FontStyle = 'default' | 'dyslexic' | 'readable' | 'serif' | 'sans' | 'mono';
export type ColorBlindFilter = 'none' | 'protanopia' | 'deuteranopia' | 'tritanopia';
export type ButtonPosition = 'bottom-right' | 'bottom-left' | 'top-right' | 'top-left';
export type PanelPosition = 'left' | 'right' | 'top' | 'bottom';

export interface AccessibilityState {
    fontSize: number;
    fontStyle: FontStyle;
    highContrast: boolean;
    grayscale: boolean;
    invertColors: boolean;
    readingGuide: boolean;
    readingGuideColor: string;
    readingGuideThickness: number;
    readingRuler: boolean;
    readingRulerColor: string;
    readingRulerWidth: number;
    readingMask: boolean;
    readingMaskColor: string;
    readingSpotlight: boolean;
    reduceMotion: boolean;
    darkMode: boolean;
    highlightLinks: boolean;
    highlightHeadings: boolean;
    cursorSize: number;
    cursorColor: string;
    pageZoom: number;
    colorBlindFilter: ColorBlindFilter;
    largeButtons: boolean;
    textToSpeech: boolean;
    speechToText: boolean;
    keyboardNavigation: boolean;
    onPageDictionary: boolean;
    textAlign: 'left' | 'center' | 'right' | 'justify';
    language: string;
    textColor: string;
    headingColor: string;
    backgroundColor: string;
    textSpacing: number;
    lineHeight: number;
    characterSpacing: number;
    buttonPosition: ButtonPosition;
    panelPosition: PanelPosition;
    hideImages: boolean;
    showImageDescriptions: boolean;
    plainTextMode: boolean;
    plainTextSize: 'small' | 'medium' | 'large';
    pauseAnimations: boolean;
    stopVideos: boolean;
    pageSummary: boolean;
    simplifiedLayout: boolean;
    summaryContent: string;
    ttsAutoPlay: boolean;
    ttsReadWholePage: boolean;
    ttsMovableControls: boolean;
    ttsVoiceGender: 'male' | 'female';
    ttsReadingSpeed: number;
    ttsReadSelectedText: boolean;
    summarizationHistory: any[];
    pronunciationGuide: boolean;
    magnifier: boolean;
    smartSuggestions: boolean;
}
